import { NextPage } from "next";
import Head from "next/head";

import { ReactNode } from "react";
import Footer from "../Footer";
import Navbar from "../Navbar";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Learning English</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div
          className="container"
          style={{
            minHeight: "calc(100vh - 140px)",
            paddingTop: "1.5em",
            paddingBottom: "1.5em",
          }}
        >
          {children}
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Layout;
